"""
Real startup-analysis production E2E validation.

C.6.1 adds one diagnostic capability to the existing real E2E:

    Document -> InvestmentProfile -> StartupAnalysisInput

The production analysis path remains unchanged when no profile observer is
provided. The E2E injects an observer into the document-intelligence service
so the exact InvestmentProfile generated by the real intelligence pipeline
can be inspected without running the document pipeline twice.

Usage:
    python -u -m scripts.startup_analysis_real_e2e
"""

from __future__ import annotations

import time
import traceback
from pathlib import Path

from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker
from sqlalchemy.pool import StaticPool

from app.core.config import settings
from app.intelligence.factory import create_intelligence_factory
from app.intelligence.models import InvestmentProfile
from app.models import Base, Document, Founder, Startup
from app.models.analysis import StartupAnalysisMode, StartupAnalysisStatus
from app.models.enums import DocumentStatus, DocumentType, FounderRole, StartupStage, StartupStatus
from app.services.document import DocumentService
from app.services.document_processing import DocumentProcessingService
from app.services.investment_intelligence import InvestmentIntelligenceService
from app.services.startup_analysis_application import StartupAnalysisApplicationService
from app.services.startup_analysis_document_intelligence import (
    StartupAnalysisDocumentIntelligenceService,
)
from app.services.startup_analysis_history import StartupAnalysisHistoryService
from app.services.startup_analysis_orchestrator import StartupAnalysisOrchestrator
from app.services.upload import UploadRequest, UploadService
from app.storage.local import LocalStorageProvider
from app.storage.service import StorageService
from app.chunking.text import TextChunker
from app.processors.factory import create_processor_factory
from app.repositories.startup_analysis import StartupAnalysisRepository


E2E_STARTUP_NAME = "Real E2E Semiconductor AI"
E2E_STARTUP_DESCRIPTION = (
    "AI-enabled semiconductor startup building edge inference "
    "solutions for surveillance applications."
)
E2E_STARTUP_SECTOR = "Semiconductor"
E2E_STARTUP_INDUSTRY = "AI"
E2E_STARTUP_FOUNDED_YEAR = 2024
E2E_STARTUP_HEADQUARTERS = "Bangalore"

E2E_FOUNDER_NAME = "E2E Founder"
E2E_FOUNDER_EXPERIENCE_YEARS = 15
E2E_FOUNDER_PREVIOUS_COMPANIES = "Company A; Company B"

E2E_MODE = StartupAnalysisMode.STANDARD

E2E_DOCUMENT_TITLE = "Real E2E Startup Investor Brief"
E2E_DOCUMENT_FILENAME = "real_e2e_startup_investor_brief.txt"
E2E_DOCUMENT_MIME_TYPE = "text/plain"
E2E_DOCUMENT_DESCRIPTION = (
    "Deterministic investment document used by the real startup-analysis E2E."
)

E2E_DOCUMENT_CONTENT = """
REAL E2E SEMICONDUCTOR AI

Company:
Real E2E Semiconductor AI builds edge AI inference solutions for surveillance
cameras and intelligent security systems.

Product:
The company is developing EdgeVision-100, an AI vision SoC for intelligent
surveillance cameras.

The product integrates:
- Image signal processing
- Video processing
- AI inference
- Edge analytics
- RISC-V based control
- Hardware acceleration

Technology:
The company develops semiconductor hardware and software for on-device AI
inference.

Target applications include:
- Surveillance cameras
- Intelligent security systems
- Edge video analytics

Market:
The initial target market is intelligent surveillance and security camera OEMs.

Geography:
India and Southeast Asia.

Business model:
The company plans to generate revenue through semiconductor SoC sales,
IP licensing, and platform integration with camera OEMs.

Financial information:
FY2025 revenue: INR 12 crore.
FY2025 EBITDA: INR 2 crore.
Cash balance: INR 8 crore.
Monthly burn: INR 0.5 crore.
Revenue growth: 50 percent.

Traction:
The company has pilot deployments with surveillance camera manufacturers.

Fundraising:
The company is evaluating a seed investment round to accelerate semiconductor
product development, customer qualification, and production readiness.

Risks:
The company depends on successful semiconductor production, customer design
wins, and execution of the product roadmap.

Management:
The founding team has semiconductor engineering experience and prior experience
at Company A and Company B.
""".strip()


# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------


def create_test_engine():
    return create_engine(
        "sqlite://",
        future=True,
        echo=False,
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )


def create_session(engine) -> Session:
    factory = sessionmaker(
        bind=engine,
        autoflush=False,
        expire_on_commit=False,
        future=True,
    )
    return factory()


# ---------------------------------------------------------------------------
# Storage / upload
# ---------------------------------------------------------------------------


def create_storage_service() -> StorageService:
    return StorageService(
        LocalStorageProvider(settings.storage_root)
    )


def create_upload_service(
    session: Session,
    storage: StorageService,
) -> UploadService:
    return UploadService(
        storage=storage,
        documents=DocumentService(session),
    )


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


def create_real_startup(session: Session) -> Startup:
    startup = Startup(
        name=E2E_STARTUP_NAME,
        legal_name=None,
        description=E2E_STARTUP_DESCRIPTION,
        sector=E2E_STARTUP_SECTOR,
        industry=E2E_STARTUP_INDUSTRY,
        stage=StartupStage.IDEA,
        status=StartupStatus.ACTIVE,
        founded_year=E2E_STARTUP_FOUNDED_YEAR,
        website=None,
        headquarters=E2E_STARTUP_HEADQUARTERS,
    )

    session.add(startup)
    session.flush()

    session.add(
        Founder(
            startup=startup,
            full_name=E2E_FOUNDER_NAME,
            designation=FounderRole.CEO,
            experience_years=E2E_FOUNDER_EXPERIENCE_YEARS,
            previous_companies=E2E_FOUNDER_PREVIOUS_COMPANIES,
            education=None,
            notes=None,
            email=None,
        )
    )

    session.commit()
    session.refresh(startup)
    return startup


def create_real_document(
    session: Session,
    startup: Startup,
    storage: StorageService,
) -> Document:
    upload_service = create_upload_service(session, storage)

    document = upload_service.upload(
        UploadRequest(
            startup_id=startup.id,
            document_type=DocumentType.OTHER,
            title=E2E_DOCUMENT_TITLE,
            filename=E2E_DOCUMENT_FILENAME,
            mime_type=E2E_DOCUMENT_MIME_TYPE,
            description=E2E_DOCUMENT_DESCRIPTION,
            data=E2E_DOCUMENT_CONTENT.encode("utf-8"),
        )
    )

    session.refresh(document)
    return document


def validate_real_document(
    storage: StorageService,
    document: Document,
    startup: Startup,
) -> None:
    assert document.id is not None
    assert document.startup_id == startup.id
    assert document.document_type == DocumentType.OTHER
    assert document.title == E2E_DOCUMENT_TITLE
    assert document.filename == E2E_DOCUMENT_FILENAME
    assert document.original_filename == E2E_DOCUMENT_FILENAME
    assert document.mime_type == E2E_DOCUMENT_MIME_TYPE
    assert document.status == DocumentStatus.UPLOADED
    assert document.file_size == len(E2E_DOCUMENT_CONTENT.encode("utf-8"))
    assert document.file_hash
    assert document.storage_path

    assert storage.exists(document.storage_path)
    assert storage.open(document.storage_path) == E2E_DOCUMENT_CONTENT.encode("utf-8")


def print_document_summary(document: Document) -> None:
    print()
    print("-" * 80)
    print("PERSISTED E2E DOCUMENT")
    print("-" * 80)
    print(f"Document ID      : {document.id}")
    print(f"Startup ID       : {document.startup_id}")
    print(f"Document type    : {document.document_type.value}")
    print(f"Title            : {document.title}")
    print(f"Filename         : {document.filename}")
    print(f"MIME type        : {document.mime_type}")
    print(f"File size        : {document.file_size}")
    print(f"File hash        : {document.file_hash}")
    print(f"Storage path     : {document.storage_path}")
    print(f"Status           : {document.status.value}")


# ---------------------------------------------------------------------------
# C.6.1 intelligence diagnostics
# ---------------------------------------------------------------------------


def _print_value(label: str, value) -> None:
    print(f"{label:<28}: {value}")


def print_investment_profile(profile: InvestmentProfile) -> None:
    """Print the raw InvestmentProfile before StartupAnalysisInput mapping."""
    print()
    print("=" * 80)
    print("INVESTMENT INTELLIGENCE EXTRACTION — C.6.1")
    print("=" * 80)
    _print_value("Document ID", profile.document_id)
    _print_value("Overall confidence", profile.confidence)

    metadata = profile.metadata
    print()
    print("-" * 80)
    print("METADATA")
    print("-" * 80)
    for name in (
        "title",
        "document_type",
        "secondary_document_types",
        "language",
        "page_count",
        "sections",
        "keywords",
        "confidence",
    ):
        _print_value(name, getattr(metadata, name, None))

    entities = profile.entities
    print()
    print("-" * 80)
    print("ENTITIES")
    print("-" * 80)
    for name in (
        "company_name",
        "founders",
        "investors",
        "accelerators",
        "locations",
        "sectors",
        "products",
        "technologies",
        "confidence",
    ):
        _print_value(name, getattr(entities, name, None))

    financials = profile.financials
    print()
    print("-" * 80)
    print("FINANCIALS")
    print("-" * 80)
    for name in (
        "currency",
        "raise_amount",
        "valuation",
        "revenue",
        "arr",
        "ebitda",
        "margin",
        "burn_rate",
        "runway_months",
        "confidence",
    ):
        _print_value(name, getattr(financials, name, None))

    signals = profile.signals
    print()
    print("-" * 80)
    print("SIGNALS")
    print("-" * 80)
    for name in (
        "stage",
        "industry",
        "business_models",
        "technologies",
        "markets",
        "geographies",
        "themes",
        "confidence",
    ):
        _print_value(name, getattr(signals, name, None))

    risks = profile.risks
    print()
    print("-" * 80)
    print("RISKS")
    print("-" * 80)
    for name in (
        "founder_risks",
        "financial_risks",
        "execution_risks",
        "market_risks",
        "technology_risks",
        "legal_risks",
        "confidence",
    ):
        _print_value(name, getattr(risks, name, None))

    print()
    print("-" * 80)
    print("EXTRAS")
    print("-" * 80)
    extras = profile.extras or {}
    if not extras:
        print("<none>")
    else:
        for name, value in extras.items():
            _print_value(name, value)


def print_mapped_input(input_snapshot: dict) -> None:
    """Print the persisted StartupAnalysisInput snapshot by analysis section."""
    print()
    print("=" * 80)
    print("STARTUP ANALYSIS INPUT AFTER DOCUMENT ENRICHMENT")
    print("=" * 80)

    for field in (
        "product",
        "market",
        "traction",
        "financials",
        "business_model",
    ):
        print()
        print(f"{field.upper()}")
        print("-" * 80)
        value = input_snapshot.get(field)
        if value is None:
            print("<empty>")
        elif isinstance(value, dict):
            for key, item in value.items():
                print(f"{key:<28}: {item}")
        else:
            print(value)


def validate_document_enrichment(analysis, profiles: list[InvestmentProfile]) -> None:
    assert profiles, "No InvestmentProfile was captured by C.6.1 observer."

    input_snapshot = analysis.input_snapshot
    assert input_snapshot is not None
    assert isinstance(input_snapshot, dict)

    fields = (
        "product",
        "market",
        "traction",
        "financials",
        "business_model",
    )

    populated = [
        field for field in fields
        if input_snapshot.get(field) is not None
    ]

    assert populated, (
        "Document was processed and an InvestmentProfile was produced, "
        "but no supported StartupAnalysisInput fields were populated."
    )

    print()
    print(
        "Document enrichment: PASS "
        f"({', '.join(populated)})"
    )


# ---------------------------------------------------------------------------
# Persisted analysis / history validation
# ---------------------------------------------------------------------------


def validate_persisted_analysis(analysis, startup: Startup) -> None:
    assert analysis is not None
    assert analysis.id is not None
    assert analysis.startup_id == startup.id
    assert analysis.status == StartupAnalysisStatus.COMPLETED
    assert analysis.mode == E2E_MODE

    assert analysis.analysis_version
    assert analysis.model_name
    assert analysis.max_tokens > 0
    assert analysis.temperature >= 0.0

    assert analysis.finish_reason is not None
    assert analysis.prompt_tokens is not None
    assert analysis.completion_tokens is not None
    assert analysis.total_tokens is not None

    assert analysis.prompt_tokens >= 0
    assert analysis.completion_tokens >= 0
    assert analysis.total_tokens >= 0

    assert isinstance(analysis.input_snapshot, dict)
    assert isinstance(analysis.metrics_snapshot, dict)
    assert isinstance(analysis.result_snapshot, dict)

    input_snapshot = analysis.input_snapshot
    assert input_snapshot["startup_id"] == str(startup.id)
    assert input_snapshot["company"]["name"] == E2E_STARTUP_NAME
    assert input_snapshot["company"]["description"] == E2E_STARTUP_DESCRIPTION
    assert input_snapshot["company"]["industry"] == E2E_STARTUP_INDUSTRY
    assert input_snapshot["company"]["sector"] == E2E_STARTUP_SECTOR
    assert input_snapshot["company"]["founded_year"] == E2E_STARTUP_FOUNDED_YEAR
    assert input_snapshot["company"]["headquarters"] == E2E_STARTUP_HEADQUARTERS

    founders = input_snapshot["founders"]
    assert len(founders) == 1
    founder = founders[0]
    assert founder["name"] == E2E_FOUNDER_NAME
    assert founder["role"] == FounderRole.CEO.value
    assert founder["relevant_experience"] == (
        f"{E2E_FOUNDER_EXPERIENCE_YEARS} years experience; "
        f"Previous companies: {E2E_FOUNDER_PREVIOUS_COMPANIES}"
    )

    assert analysis.created_at is not None
    assert analysis.updated_at is not None


def validate_history_round_trip(
    history_service: StartupAnalysisHistoryService,
    startup: Startup,
    analysis,
) -> None:
    items, total_items = history_service.list_history(
        startup.id,
        page=1,
        per_page=20,
    )

    assert total_items == 1
    assert len(items) == 1

    history_item = items[0]
    assert history_item.id == analysis.id
    assert history_item.startup_id == startup.id
    assert history_item.mode == E2E_MODE
    assert history_item.status == StartupAnalysisStatus.COMPLETED

    historical = history_service.get_history(
        startup.id,
        analysis.id,
    )

    assert historical is not None
    assert historical.id == analysis.id
    assert historical.startup_id == startup.id
    assert historical.input_snapshot == analysis.input_snapshot
    assert historical.metrics_snapshot == analysis.metrics_snapshot
    assert historical.result_snapshot == analysis.result_snapshot


def print_analysis_summary(analysis) -> None:
    print()
    print("-" * 80)
    print("PERSISTED ANALYSIS")
    print("-" * 80)
    print(f"Analysis ID      : {analysis.id}")
    print(f"Startup ID       : {analysis.startup_id}")
    print(f"Status           : {analysis.status.value}")
    print(f"Mode             : {analysis.mode.value}")
    print(f"Model            : {analysis.model_name}")
    print(f"Thinking         : {analysis.thinking_enabled}")
    print(f"Max tokens       : {analysis.max_tokens}")
    print(f"Temperature      : {analysis.temperature}")
    print()
    print("LLM metadata:")
    print(f"  Finish reason  : {analysis.finish_reason}")
    print(f"  Prompt tokens  : {analysis.prompt_tokens}")
    print(f"  Completion     : {analysis.completion_tokens}")
    print(f"  Total tokens   : {analysis.total_tokens}")
    print()
    print("Artifacts:")
    print(f"  Input snapshot   : {'YES' if analysis.input_snapshot else 'NO'}")
    print(f"  Metrics snapshot : {'YES' if analysis.metrics_snapshot else 'NO'}")
    print(f"  Result snapshot  : {'YES' if analysis.result_snapshot else 'NO'}")
    if analysis.recommendation is not None:
        print(f"  Recommendation   : {analysis.recommendation}")


def cleanup_document_storage(
    storage: StorageService | None,
    document: Document | None,
) -> None:
    if storage is None or document is None or not document.storage_path:
        return

    try:
        if storage.exists(document.storage_path):
            storage.delete(document.storage_path)
    except Exception as exc:
        print("WARNING: Failed to remove E2E document from storage:")
        print(f"         {document.storage_path}")
        print(f"         {exc}")


def print_header() -> None:
    print("=" * 80)
    print("REAL STARTUP ANALYSIS E2E — C.6.1")
    print("=" * 80)
    print(f"Model path       : {settings.qwen_model_path}")
    print(f"Qwen threads     : {settings.qwen_threads}")
    print(f"Context size     : {settings.qwen_context_size}")
    print(f"Thinking         : {settings.qwen_enable_thinking}")
    print(f"Max tokens       : {settings.startup_analysis_max_tokens}")
    print(f"Temperature      : {settings.startup_analysis_temperature}")
    print(f"Analysis mode    : {E2E_MODE.value}")
    print()
    print(f"Startup          : {E2E_STARTUP_NAME}")
    print(f"Founder          : {E2E_FOUNDER_NAME}")
    print(f"Document         : {E2E_DOCUMENT_FILENAME}")


def main() -> int:
    print_header()

    model_path = Path(settings.qwen_model_path)
    if not model_path.exists():
        print()
        print("ERROR: Qwen model file does not exist.")
        print(f"       {model_path}")
        return 1

    storage = create_storage_service()
    engine = create_test_engine()
    startup: Startup | None = None
    document: Document | None = None
    captured_profiles: list[InvestmentProfile] = []

    def capture_profile(profile: InvestmentProfile) -> None:
        captured_profiles.append(profile)

    try:
        print()
        print("-" * 80)
        print("Creating E2E database")
        print("-" * 80)
        Base.metadata.create_all(engine)

        session = create_session(engine)
        try:
            print()
            print("-" * 80)
            print("Creating startup fixture")
            print("-" * 80)
            startup = create_real_startup(session)
            print(f"Startup ID       : {startup.id}")

            print()
            print("-" * 80)
            print("Creating real document fixture")
            print("-" * 80)
            document = create_real_document(session, startup, storage)
            print(f"Document ID      : {document.id}")

            validate_real_document(storage, document, startup)
            print_document_summary(document)
            print()
            print("Document persistence/storage: PASS")

            session.refresh(startup)
            documents = list(startup.documents or [])
            assert any(item.id == document.id for item in documents)
            print("Startup -> Document relationship: PASS")

            # ----------------------------------------------------------
            # C.6.1 diagnostic observer
            # ----------------------------------------------------------
            # Build the same production document-intelligence dependency
            # graph used by the application factory, but inject the
            # diagnostic observer. The application service still owns
            # startup resolution and persistence; only the orchestrator
            # dependency is supplied explicitly so C.6.1 can inspect the
            # raw InvestmentProfile without a second document-analysis pass.
            documents_service = DocumentService(session)
            processing = DocumentProcessingService(
                documents=documents_service,
                storage=storage,
                processors=create_processor_factory(),
                chunker=TextChunker(),
            )
            intelligence = InvestmentIntelligenceService(
                factory=create_intelligence_factory(),
            )
            document_intelligence = (
                StartupAnalysisDocumentIntelligenceService(
                    document_processing=processing,
                    intelligence=intelligence,
                    profile_observer=capture_profile,
                )
            )
            orchestrator = StartupAnalysisOrchestrator(
                document_intelligence_service=document_intelligence,
            )

            print()
            print("-" * 80)
            print("Running production startup analysis")
            print("-" * 80)
            print()
            print("IMPORTANT: This invokes the real Qwen GGUF model.")
            print("C.6.1 captures the raw InvestmentProfile before mapping.")
            print()

            analysis_start = time.perf_counter()

            application_service = StartupAnalysisApplicationService(
                session=session,
                orchestrator=orchestrator,
            )

            analysis = application_service.analyze(
                startup_id=startup.id,
                mode=E2E_MODE,
            )

            elapsed = time.perf_counter() - analysis_start
            print(f"Analysis time    : {elapsed:.2f} sec")

            # ----------------------------------------------------------
            # C.6.1 raw profile diagnostics
            # ----------------------------------------------------------
            assert captured_profiles
            for profile in captured_profiles:
                print_investment_profile(profile)

            print()
            print("-" * 80)
            print("Validating persisted analysis")
            print("-" * 80)
            validate_persisted_analysis(analysis, startup)
            print("Persistence validation: PASS")

            print()
            print("-" * 80)
            print("Validating document intelligence enrichment")
            print("-" * 80)
            validate_document_enrichment(analysis, captured_profiles)
            print_mapped_input(analysis.input_snapshot)

            print_analysis_summary(analysis)

            print()
            print("-" * 80)
            print("Validating analysis history")
            print("-" * 80)
            repository = StartupAnalysisRepository(session)
            history_service = StartupAnalysisHistoryService(
                repository=repository,
            )
            validate_history_round_trip(
                history_service,
                startup,
                analysis,
            )
            print("History round-trip: PASS")

            print()
            print("=" * 80)
            print("REAL STARTUP ANALYSIS E2E: PASS")
            print("=" * 80)
            print()
            print("Validated:")
            print("  [PASS] Real Startup ORM")
            print("  [PASS] Real Founder ORM")
            print("  [PASS] Real UploadService")
            print("  [PASS] Real StorageService")
            print("  [PASS] Real Document ORM")
            print("  [PASS] Document storage round-trip")
            print("  [PASS] Startup -> Document relationship")
            print("  [PASS] StartupAnalysisApplicationService")
            print("  [PASS] StartupAnalysisOrchestrator")
            print("  [PASS] AnalysisInputBuilder")
            print("  [PASS] DocumentProcessingService")
            print("  [PASS] InvestmentIntelligenceService")
            print("  [PASS] Raw InvestmentProfile captured")
            print("  [PASS] Document intelligence enrichment")
            print("  [PASS] FinancialMetricsService")
            print("  [PASS] Real QwenProvider")
            print("  [PASS] StartupAnalysisParser")
            print("  [PASS] StartupAnalysisExecution")
            print("  [PASS] StartupAnalysisPersistenceService")
            print("  [PASS] StartupAnalysisMapper")
            print("  [PASS] StartupAnalysisRepository")
            print("  [PASS] Persisted execution artifacts")
            print("  [PASS] StartupAnalysisHistoryService")
            print()
            return 0

        finally:
            session.close()

    except Exception as exc:
        print()
        print("=" * 80)
        print("REAL STARTUP ANALYSIS E2E: FAILED")
        print("=" * 80)
        print()
        print(f"Exception type   : {type(exc).__name__}")
        print(f"Exception        : {exc}")
        print()
        traceback.print_exc()
        return 1

    finally:
        cleanup_document_storage(storage, document)
        Base.metadata.drop_all(engine)
        engine.dispose()


if __name__ == "__main__":
    raise SystemExit(main())
