"""add_role_permissions_table

Revision ID: 3ec86673f381
Revises: 483d1e3d7155
Create Date: 2026-08-08 12:22:35.678775+00:00
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# ---------------------------------------------------------------------------
# Alembic Revision Identifiers
# ---------------------------------------------------------------------------

revision = "3ec86673f381"
down_revision = "483d1e3d7155"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply database schema changes."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.Column("granted_by", sa.UUID(), nullable=True),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["granted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id", "permission_id", name="uq_role_permissions_role_permission"),
    )
    op.create_index(
        "ix_role_permissions_permission_id", "role_permissions", ["permission_id"], unique=False
    )
    op.create_index("ix_role_permissions_role_id", "role_permissions", ["role_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert database schema changes."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_role_permissions_role_id", table_name="role_permissions")
    op.drop_index("ix_role_permissions_permission_id", table_name="role_permissions")
    op.drop_table("role_permissions")
    # ### end Alembic commands ###
