"""initial_schema

Revision ID: 8c2010bb7831
Revises: 
Create Date: 2026-08-08 10:47:49.692793+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# ---------------------------------------------------------------------------
# Alembic Revision Identifiers
# ---------------------------------------------------------------------------

revision = '8c2010bb7831'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply database schema changes."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('startups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.Enum('IDEA', 'MVP', 'EARLY_REVENUE', 'GROWTH', 'SCALE', name='startupstage'), nullable=False),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('headquarters', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='startupstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startups_name'), 'startups', ['name'], unique=False)
    op.create_index(op.f('ix_startups_sector'), 'startups', ['sector'], unique=False)
    op.create_index(op.f('ix_startups_status'), 'startups', ['status'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('documents',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('PITCH_DECK', 'FINANCIAL_MODEL', 'BUSINESS_PLAN', 'TERM_SHEET', 'SHA', 'CAP_TABLE', 'BANK_STATEMENT', 'GST', 'ROC', 'PATENT', 'PRODUCT_DEMO', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'PROCESSED', 'FAILED', 'ARCHIVED', name='documentstatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=True)
    op.create_index(op.f('ix_documents_startup_id'), 'documents', ['startup_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('founders',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.Enum('CEO', 'CTO', 'COO', 'CFO', 'CMO', 'CPO', 'CHAIRMAN', 'DIRECTOR', 'ADVISOR', 'OTHER', name='founderrole'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('education', sa.String(length=255), nullable=True),
    sa.Column('previous_companies', sa.Text(), nullable=True),
    sa.Column('ownership_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_primary_contact', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_founders_startup_id'), 'founders', ['startup_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('round_name', sa.String(length=100), nullable=False),
    sa.Column('instrument', sa.Enum('EQUITY', 'CCPS', 'CCD', 'SAFE', 'CONVERTIBLE_NOTE', name='investmentinstrument'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'FULLY_SUBSCRIBED', 'CANCELLED', name='opportunitystatus'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('target_raise', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('minimum_ticket', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valuation_cap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pre_money_valuation', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('post_money_valuation', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('committed_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('soft_committed_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('investment_thesis', sa.Text(), nullable=True),
    sa.Column('risk_summary', sa.Text(), nullable=True),
    sa.Column('analyst_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_startup_id'), 'opportunities', ['startup_id'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_table('investments',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WATCHLIST', name='investmentdecision'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'EXECUTED', 'DECLINED', 'EXITED', name='investmentstatus'), nullable=False),
    sa.Column('investment_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ownership_target', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('expected_ownership', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('investment_date', sa.Date(), nullable=True),
    sa.Column('investment_lead', sa.String(length=255), nullable=True),
    sa.Column('committee_reference', sa.String(length=100), nullable=True),
    sa.Column('requires_followup', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_decision'), 'investments', ['decision'], unique=False)
    op.create_index(op.f('ix_investments_opportunity_id'), 'investments', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_investments_status'), 'investments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert database schema changes."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investments_status'), table_name='investments')
    op.drop_index(op.f('ix_investments_opportunity_id'), table_name='investments')
    op.drop_index(op.f('ix_investments_decision'), table_name='investments')
    op.drop_table('investments')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_startup_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_founders_startup_id'), table_name='founders')
    op.drop_table('founders')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_startup_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_startups_status'), table_name='startups')
    op.drop_index(op.f('ix_startups_sector'), table_name='startups')
    op.drop_index(op.f('ix_startups_name'), table_name='startups')
    op.drop_table('startups')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
