"""add_permissions_table

Revision ID: 9a1b5cd3d72b
Revises: 8c2010bb7831
Create Date: 2026-08-08 11:15:39.559876+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# ---------------------------------------------------------------------------
# Alembic Revision Identifiers
# ---------------------------------------------------------------------------

revision = '9a1b5cd3d72b'
down_revision = '8c2010bb7831'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply database schema changes."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert database schema changes."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
