"""add_cbo_founder_role

Revision ID: abcb4ef9ee89
Revises: 3ec86673f381
Create Date: 2026-08-21 05:42:59.197960+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# ---------------------------------------------------------------------------
# Alembic Revision Identifiers
# ---------------------------------------------------------------------------

revision = 'abcb4ef9ee89'
down_revision = '3ec86673f381'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply database schema changes."""

    op.execute(
        "ALTER TYPE founderrole ADD VALUE IF NOT EXISTS 'CBO'"
    )



def downgrade() -> None:
    """Revert database schema changes."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_startup_analyses_startup_id'), table_name='startup_analyses')
    op.drop_index('ix_startup_analyses_startup_created', table_name='startup_analyses')
    op.drop_table('startup_analyses')
    # ### end Alembic commands ###
