"""add_cbo_founder_role_enum

Revision ID: ff1b6d4c1d1b
Revises: e7ffc539bd4f
Create Date: 2026-08-21 06:00:15.923551+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# ---------------------------------------------------------------------------
# Alembic Revision Identifiers
# ---------------------------------------------------------------------------

revision = 'ff1b6d4c1d1b'
down_revision = 'e7ffc539bd4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        "ALTER TYPE founderrole ADD VALUE IF NOT EXISTS 'CBO'"
    )

def downgrade() -> None:
    """Revert database schema changes."""

    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
