"""
API schemas for startup analysis.

This module defines the HTTP request/response contracts for the
startup-analysis API.

Responsibilities:
    - Validate API requests.
    - Represent persisted startup-analysis results for API consumers.
    - Provide ORM-compatible response serialization.
    - Represent startup-analysis history.

Non-responsibilities:
    - Analysis calculations.
    - Analysis orchestration.
    - Prompt construction.
    - LLM execution.
    - Response parsing.
    - Persistence.
    - Transaction management.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any
from uuid import UUID

from pydantic import Field

from app.models.analysis import (
    StartupAnalysisMode,
    StartupAnalysisStatus,
)
from app.schemas.base import BaseSchema
from app.schemas.pagination import PaginationMeta


# =============================================================================
# Analysis Request
# =============================================================================


class StartupAnalysisRequest(BaseSchema):
    """
    Request to execute a startup analysis.

    The API deliberately exposes only the analysis mode.

    Generation parameters such as model, thinking mode, max tokens,
    and temperature are resolved internally by StartupAnalysisConfig.
    """

    mode: StartupAnalysisMode = Field(
        default=StartupAnalysisMode.STANDARD,
        description=(
            "Analysis depth. STANDARD provides the normal analysis; "
            "DEEP enables extended reasoning."
        ),
        examples=[
            StartupAnalysisMode.STANDARD,
        ],
    )


# =============================================================================
# Analysis Response
# =============================================================================


class StartupAnalysisResponse(BaseSchema):
    """
    API representation of a persisted startup-analysis execution.

    This represents the historical analysis record, not the internal
    StartupAnalysisExecution domain envelope.

    Historical snapshots are intentionally excluded from this summary
    response. They are exposed through the analysis-history detail API.
    """

    id: UUID = Field(
        ...,
        description="Unique identifier of the startup analysis.",
    )

    startup_id: UUID = Field(
        ...,
        description="Identifier of the startup that was analyzed.",
    )

    mode: StartupAnalysisMode = Field(
        ...,
        description="Analysis mode used for this execution.",
    )

    status: StartupAnalysisStatus = Field(
        ...,
        description="Lifecycle status of the analysis.",
    )

    analysis_version: str = Field(
        ...,
        description="Version of the startup-analysis pipeline.",
        examples=["3.7.5"],
    )

    # ------------------------------------------------------------------
    # LLM execution configuration
    # ------------------------------------------------------------------

    model_name: str = Field(
        ...,
        description="LLM model used for the analysis.",
        examples=["Qwen3-8B-Q4_K_M"],
    )

    thinking_enabled: bool = Field(
        ...,
        description="Whether extended model thinking was enabled.",
    )

    max_tokens: int = Field(
        ...,
        description="Maximum number of generated tokens.",
        examples=[768],
    )

    temperature: float = Field(
        ...,
        description="LLM generation temperature.",
        examples=[0.0],
    )

    # ------------------------------------------------------------------
    # LLM execution metadata
    # ------------------------------------------------------------------

    finish_reason: str | None = Field(
        default=None,
        description="Provider-reported generation completion reason.",
        examples=["stop"],
    )

    prompt_tokens: int | None = Field(
        default=None,
        description="Number of tokens consumed by the prompt.",
        examples=[1400],
    )

    completion_tokens: int | None = Field(
        default=None,
        description="Number of tokens generated by the model.",
        examples=[500],
    )

    total_tokens: int | None = Field(
        default=None,
        description="Total prompt plus completion tokens.",
        examples=[1900],
    )

    inference_time_seconds: float | None = Field(
        default=None,
        description="Wall-clock inference duration in seconds.",
        examples=[150.0],
    )

    # ------------------------------------------------------------------
    # Analysis conclusion
    # ------------------------------------------------------------------

    recommendation: str | None = Field(
        default=None,
        description="Investment recommendation produced by the analysis.",
    )

    investment_thesis: str | None = Field(
        default=None,
        description="Investment thesis produced by the analysis.",
    )

    # ------------------------------------------------------------------
    # Timestamps
    # ------------------------------------------------------------------

    created_at: datetime = Field(
        ...,
        description="UTC timestamp when the analysis record was created.",
    )

    updated_at: datetime = Field(
        ...,
        description="UTC timestamp when the analysis record was last updated.",
    )


# =============================================================================
# Analysis History Item
# =============================================================================


class StartupAnalysisHistoryItem(BaseSchema):
    """
    Lightweight representation of one historical startup analysis.

    Used by the paginated analysis-history list endpoint.

    Historical snapshots are intentionally excluded because the list
    endpoint should remain lightweight.
    """

    id: UUID = Field(
        ...,
        description="Unique identifier of the startup analysis.",
    )

    startup_id: UUID = Field(
        ...,
        description="Identifier of the startup that was analyzed.",
    )

    mode: StartupAnalysisMode = Field(
        ...,
        description="Analysis mode used for this execution.",
    )

    status: StartupAnalysisStatus = Field(
        ...,
        description="Lifecycle status of the analysis.",
    )

    analysis_version: str = Field(
        ...,
        description="Version of the startup-analysis pipeline.",
        examples=["3.7.5"],
    )

    model_name: str = Field(
        ...,
        description="LLM model used for the analysis.",
        examples=["Qwen3-8B-Q4_K_M"],
    )

    thinking_enabled: bool = Field(
        ...,
        description="Whether extended model thinking was enabled.",
    )

    max_tokens: int = Field(
        ...,
        description="Maximum number of generated tokens.",
        examples=[768],
    )

    temperature: float = Field(
        ...,
        description="LLM generation temperature.",
        examples=[0.0],
    )

    recommendation: str | None = Field(
        default=None,
        description="Investment recommendation produced by the analysis.",
    )

    created_at: datetime = Field(
        ...,
        description="UTC timestamp when the analysis record was created.",
    )

    updated_at: datetime = Field(
        ...,
        description="UTC timestamp when the analysis record was last updated.",
    )


# =============================================================================
# Analysis History Detail
# =============================================================================


class StartupAnalysisHistoryResponse(StartupAnalysisResponse):
    """
    Complete historical representation of a startup-analysis execution.

    Unlike StartupAnalysisResponse, this response exposes the immutable
    execution snapshots persisted with the analysis.
    """

    input_snapshot: dict[str, Any] = Field(
        ...,
        description=(
            "JSON snapshot of the normalized analysis input used "
            "for this execution."
        ),
    )

    metrics_snapshot: dict[str, Any] = Field(
        ...,
        description=(
            "JSON snapshot of the deterministic financial metrics "
            "calculated for this execution."
        ),
    )

    result_snapshot: dict[str, Any] = Field(
        ...,
        description=(
            "JSON snapshot of the structured qualitative analysis "
            "result produced by the LLM pipeline."
        ),
    )

    error_message: str | None = Field(
        default=None,
        description="Error message recorded when the analysis failed.",
    )


# =============================================================================
# Paginated History
# =============================================================================


class StartupAnalysisHistoryPage(BaseSchema):
    """
    Paginated startup-analysis history.
    """

    items: list[StartupAnalysisHistoryItem] = Field(
        ...,
        description="Analysis history items for the requested page.",
    )

    pagination: PaginationMeta = Field(
        ...,
        description="Pagination metadata for the history collection.",
    )


__all__ = [
    "StartupAnalysisRequest",
    "StartupAnalysisResponse",
    "StartupAnalysisHistoryItem",
    "StartupAnalysisHistoryResponse",
    "StartupAnalysisHistoryPage",
]
